### ISSUE TITLE
Foot note and check mark not working

### ISSUE THREAD

**Issue by yw662** [arguablykomodo/deno_rusty_markdown#2]
The testing markdown is like this:
```markdown
#Asdf

asdsaf\`asdf\`asdf[^1]
[x] asdf
[ ] asdf
[^1]: This is a footnote content.
```

However, it gives out text tokens instead of `footnoteReference` or `taskListMarker`.
Does the underlying rust library really support foot note or task list mark ?

**Comment by arguablykomodo** [comment]
Have you enabled the `footnotes` and `tasklists` options? `tokens(yourText, { footnotes: true, tasklists: true })` should do the trick.

**Comment by arguablykomodo** [comment]
On further inspection, it seems your example text doesn't work due to wrong syntax. A working example would be:

```md
# Asdf

asdsaf\`asdf\`asdf[^1]
- [x] asdf
- [ ] asdf

[^1]: This is a footnote content.
```

The parser requires:
- A space after the `#` on headings.
- An empty line between the end of a list and a footnote definition.
- Dashes on tasklists, just like ordered or unordered lists.
